### ISSUE TITLE
Network Traffic should not count specific connections

### ISSUE THREAD

**Issue by majst01** [metal-stack/firewall-controller#10]
It must be possible to exclude network traffic which is partition local for example.
This can be achieved by switching network accounting from a interface based accounting to nftables based counters. We must then create counter rules for "ignored" networks and all other networks per vrf id.

The list if ignored networks is stored in the firewall crd. This is done from the gardener-extension-provider-metal which will ask metal-api to get these networks.

@mwennrich @mwindower

**Comment by mwindower** [comment]
Actually the list of internal networks is provided at the accounting exporter and consumed from the gepm.
