### ISSUE TITLE
Egress Policies not updating anymore when no changes on CWNPs occur

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/firewall-controller#105]
Regression probably caused by https://github.com/metal-stack/firewall-controller/pull/96

Please consider adding more relevant fields to checksum calculation (`firewall.spec.data` field is a good candidate).

**Comment by Gerrit91** [comment]
Also when removing a CWNP, the rules are not deleted anymore.

**Comment by Gerrit91** [comment]
Also service type load balancer flow is broken.

**Comment by majst01** [comment]
I very simple approach to ensure a reload occurs on any structural changes in the nftables file would be to create the checksum over the sorted file. Simply sort (line by line) the file before creating the checksum.

**Comment by Gerrit91** [comment]
Fixed through #109 .
