### ISSUE TITLE
DNS proxy does not work with fixed internet egress address

### ISSUE THREAD

**Issue by mreiger** [metal-stack/firewall-controller#133]
The DNS proxy for dns-based clusterwidenetworkpolicies does not work when a fixed egress IP is defined in the cluster because the firewall rules conflict.

Rules example where `192.168.1.1` is the fixed egress IP and `192.168.1.5` is the firewall IP:
```
table inet firewall {
(...)
        chain postrouting {
                type nat hook postrouting priority filter - 1; policy accept;
                ip saddr { 10.1.4.0/22 } oifname "vlan104009" counter packets 168188 bytes 14511193 snat ip to 192.168.1.1 comment "snat for internet"
                ip saddr { 10.1.4.0/22 } oifname "vlan104010" counter packets 397 bytes 23820 snat ip to 100.64.1.2 comment "snat for secondary network"
        }
}
table inet metal {
        chain input {
(...)
                ip saddr 10.0.0.0/8 tcp dport 53 ip daddr 192.168.1.5 accept comment "dnat to dns proxy"
                ip saddr 10.0.0.0/8 udp dport 53 ip daddr 192.168.1.5 accept comment "dnat to dns proxy"
```

Likely cause: The postrouting chain of the firewall table comes before the input chain of the metal table, therefore the snat rule changes the source address of the DNS packets so the input rule for the dns proxy no longer matches.

Two possible solutions:
- Exempt DNS packets from egress SNAT
- Add SNAT Ip(s) to dns proxy input rule

**Comment by GrigoriyMikhalkin** [comment]
https://en.wikipedia.org/wiki/Netfilter#/media/File:Netfilter-packet-flow.svg

`Postrouting` chain should work only in case of forwarding or outputing the packet. I believe, input chain still should receive unSNATed packet, am i wrong?

**Comment by mreiger** [comment]
I see what you mean; and when I look at the flow chart you linked I come to the same conclusion.

However when there's an egress SNAT IP in the internet network, DNS fails (for both pods and nodes) in the cluster; and if I remove the SNAT Ip the line
```
                ip saddr { 10.1.4.0/22 } oifname "vlan104009" counter packets 168188 bytes 14511193 snat ip to 192.168.1.1 comment "snat for internet"
```

goes away; and then DNS starts working again.

So I'm a bit puzzled. I made a firewallcontroller that would bypass SNAT for DNS packets; we can try that in test unless that is too broken at the moment. :laughing:

**Comment by mreiger** [comment]
Well; I could reproduce the problem in test. When the DNS proxy is in effect and there's an egress SNAT address, DNS fails.

The firewallcontroller from the pull request does fix it. The egress SNAT block in the firewall table looks like this then:

```
        chain postrouting {
                type nat hook postrouting priority filter - 1; policy accept;
                ip saddr { 10.128.160.0/22 } tcp dport { 53 } accept comment "escape snat for dns proxy tcp"
                ip saddr { 10.128.160.0/22 } udp dport { 53 } accept comment "escape snat for dns proxy udp"
                ip saddr { 10.128.160.0/22 } oifname "vlan104009" counter packets 42 bytes 2536 snat ip to 212.34.83.23 comment "snat for internet"
        }
```

(Only when the DNS proxy is deployed.)

**Comment by GrigoriyMikhalkin** [comment]
I guess, in case of DNAT in input, packet actually reaches `postrouting` hook. Which is, even logically, would be anticipated, since packet is forwarded.
