### ISSUE TITLE
make ssh access restricted

### ISSUE THREAD

**Issue by majst01** [metal-stack/firewall-controller#36]
Currently ssh access to the firewall is open to the public internet. This is fine for most scenarios, but someone could argue that this is more than required, "need to know principle".

To achieve this we can extend the firewall crd to a list of allowed source networks from which direct ssh access is allowed. If none is given, all networks are allowed (0.0.0.0/0)

**Comment by majst01** [comment]
@chbmuc @michaelottofits

**Comment by Gerrit91** [comment]
Should be obsoleted by MEP-9: https://github.com/metal-stack/docs/pull/99
Can we close?
