### ISSUE TITLE
Self-Reconcilation

### ISSUE THREAD

**Issue by mwindower** [metal-stack/firewall-controller#57]
The firewall crd should contain a firewall-controller version that is managed by gardener-extension-provider-metal.

The firewall-controller checks for changes and replaces itself, exits and gets restarted by systemd in the new version.

With that, we could also use the release-drafter approach and hold the firewall-controller version in the release vector.

**Comment by majst01** [comment]
This sounds quite easy to achieve, the only action to be taken is to render the version into the systemd-service file
