### ISSUE TITLE
Export const clusterwideNPNamespace

### ISSUE THREAD

**Issue by LimKianAn** [metal-stack/firewall-controller#70]
Only the `ClusterwideNetworkPolicy` under namespace [clusterwideNPNamespace](https://github.com/metal-stack/firewall-controller/blob/ad2e46aca365e95e142c013024b688110f143df7/controllers/clusterwidenetworkpolicy_controller.go#L55) will be reconciled by the reconciler. However, this const is not exported in the [api](https://github.com/metal-stack/firewall-controller/blob/master/api/v1/clusterwidenetworkpolicy_types.go). Please export the `const`, so that the user can avoid a hard-coded `string`.

**Comment by majst01** [comment]
done with #71
