### ISSUE TITLE
proposal: remove ClusterwideNetworkPolicyReconciler

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [metal-stack/firewall-controller#78]
[Comment states](https://github.com/metal-stack/firewall-controller/blob/master/controllers/clusterwidenetworkpolicy_controller.go#L40) that this reconciler supposed to create nftables rules, but in fact it only validates resource. nftables rules created/updated via firewall-controller. Should we move validation to firewall controller and remove `ClusterwideNetworkPolicyReconciler`? IMO, if there's no plans to move `ClusterwideNetworkPolicy` reconcilation there, it's quite redundant to have reconciler only for validation.

cc @majst01, @mwennrich

**Comment by majst01** [comment]
already part of #82
