### ISSUE TITLE
DNS based policy for egress

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [metal-stack/firewall-controller#79]
Support DNS based policies for egress. Similar to DNS based policies in [cilium](https://docs.cilium.io/en/v1.9/policy/language/).
As part of the solution we also need to implement DNS proxy.

**Comment by majst01** [comment]
There is already another implementation which acts as a dns proxy and put the entries into a ipset:
- https://github.com/nadoo/glider
- https://github.com/nadoo/ipset

**Comment by majst01** [comment]
After reading nftables documentation i think we can not use ipset, instead nft sets/maps/verdict maps must be used. We already use the in the accounting logic. General approach is still the same.

see: http://wiki.nftables.org/wiki-nftables/index.php/Sets

**Comment by mwindower** [comment]
Nice hint to nadoo/glider! We really must capture&cache all DNS traffic. Not only queries that target the current set of `toFQDNs` of all ClusterwideNetworkPolicies. In a running setup we want to be able to change those rules and get them applied immediately and don't want to wait for DNS requests coming by (with systemd-resolved and CoreDNS in Kubernetes we have two "caches").

**Comment by GrigoriyMikhalkin** [comment]
So we can have architecture like this:
 __________________                                                          _____________                                                    ______________    
|                                    |     reads DNS entries from cache   |                           |      writes DNS data to cache  |                            |
|    CWNP Controller       <------------------------------------------       DNS Cache      <-------------------------------------        DNS Proxy     |
|__________________|                                                        |_____________ |                                                 |______________|

Where DNS Proxy is based on glider. It monitors and caches all DNS data in DNS Cache. And then CWNP controller, when it receives resource with `toFQDN` field, looks up entries for domain names in DNS Cache. One problem is with `matchPattern`s -- it looks like the only way in that case is to do a brute search for domain names(i.e. iterate over all entries in DNS Cache).

**Comment by GrigoriyMikhalkin** [comment]
Or, i can create named sets via DNS Proxy. But still, i need to store associations to these named sets in DNS Cache(because set names are very limited, for example no longer than 16 chars). And then tie them to rules in CWNP Controller.

**Comment by GrigoriyMikhalkin** [comment]
[Cilium](https://github.com/cilium/cilium/blob/master/pkg/fqdn/dnsproxy/proxy.go) uses [miekg/dns](https://github.com/miekg/dns), which, IMO, looks much simpler than glider.

Also, cilium blocks DNS requests in proxy. Would it be redundant in our case?

**Comment by mwindower** [comment]
> So we can have architecture like this:
> 
> ```
> CWNP Controller <--- reads DNS entries from cache --- DNS Cache <--- writes DNS data to cache --- DNS Proxy
> ```
> 
> Where DNS Proxy is based on glider. It monitors and caches all DNS data in DNS Cache. And then CWNP controller, when it receives resource with `toFQDN` field, looks up entries for domain names in DNS Cache. One problem is with `matchPattern`s -- it looks like the only way in that case is to do a brute search for domain names(i.e. iterate over all entries in DNS Cache).

Cilium does the same: https://github.com/cilium/cilium/blob/641c0f9b3072a014c9541ecaa4e00a2b24c98d97/pkg/fqdn/cache.go#L425

**Comment by Gerrit91** [comment]
Let's make an appoint for reviewing this one please. @majst01 Can you maybe schedule something in the next time when you think you have some time left? It would be so nice to finish this up...

**Comment by majst01** [comment]
done with #82
